### ISSUE TITLE
Graphical wireless scanning for Linux

### ISSUE THREAD

**Issue by crismblog** [Rogentos/kogaion-desktop#30]
LinSSID is graphically and functionally similar to Inssider (Microsoft™ Windows®). It is written in C++ using Linux wireless tools, Qt5, and Qwt 6.1.

http://gpo.zugaina.org/net-wireless/linssid
http://sourceforge.net/projects/linssid/

**Comment by BlackNoxis** [comment]
Add the files and do a pull request in the repo.

**Comment by V3n3RiX** [comment]
solved, no longer need to keep this open.
